Repository heysagnik/screenREC, pull requests merged in 2022-10, with the labels that each got.

#27 Fixed video scaling issue
  src/scss/components/recorder.scss
Labels: hacktoberfest-accepted

#31 Feat: save color scheme to local storage
  src/js/components/themeToggler.js
Labels: hacktoberfest-accepted

#32 Fix: app crash after clicking `Stop Sharing` button
  src/js/components/recorder.js
Labels: hacktoberfest-accepted

#39 Detect mobile device
  src/js/index.js
  src/js/utils/handleMobileUsers.js
Labels: hacktoberfest-accepted

#42 fix: stopping tab record by clicking 'stop sharing' button crashes the app
  src/js/components/recorder.js
Labels: hacktoberfest-accepted

#36 Added Star button
  package-lock.json
  src/index.pug
  src/partials/head.pug
  src/partials/star-fork.pug
  src/scss/components/star-fork.scss
  src/scss/index.scss
Labels: hacktoberfest-accepted

#41 Pause and Resume implemented
  src/images/pause.svg
  src/images/resume.svg
  src/js/components/recorder.js
  src/partials/recorder.pug
  src/scss/components/recorder.scss
Labels: help wanted, hacktoberfest-accepted

#50 chore(readme): update the installation guide for windows
  README.md
Labels: enhancement, hacktoberfest-accepted

#62 Webcam and Audio Error Alert if Device not found
  src/js/components/recorder.js
  src/partials/recorder.pug
Labels: hacktoberfest-accepted

#55 glassmorphism added to buttons and video preview
  src/scss/components/recorder.scss
  src/scss/index.scss
Labels: hacktoberfest, hacktoberfest-accepted

#64 βeta
  src/images/pause.svg
  src/images/resume.svg
  src/js/components/recorder.js
  src/partials/recorder.pug
  src/partials/toast.pug
  src/scss/components/toast.scss
Labels: hacktoberfest-accepted

#80 Added privacy policy.md
  screenREC Privacy Policy.md
Labels: hacktoberfest-accepted
